# Generated by Django 4.2.16 on 2024-11-13 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deparname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=50)),
                ('Depar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collageapp.departmnet')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
